name: Build and push images to ECR  and deploy to AWS ECS
on:
  push:
    branches:
      - main

jobs:
  build and push ecr image:
  name: Build and push to Amazon ECR
  run-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Install Utilities
    run: |
      sudo apt-get update
      sudo apt-get install -y jq unzip
# will be taken from github actions secrets
  - name: configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-west-2

  - name: Login to Amazon ECR
    id: login-ecr
    uses: aws-actions/amazon-ecr-login@v1

  - name: Build, tag, and push image to Amazon ECR
    env:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: latest
    
    run: |
      docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$E

   
    